---
research_alpha_opportunities:
  description: 
   Conduct quantitative, technical, fundamental, sentiment, and other research analysis to identify alpha opportunities in the crypto market. 
   Generate signals that indicate alpha opportunities across different time horizons - near-term, mid-term, and long-term. 
   Collect, process and monitor macro indicators, onchain metrics, price movements, trading volumes, economic indicators, news sentiment, 
   and other relevant factors to identify opportunities, market trends and anomalies. 
   Near-term strategy and position development and maintenance focused on short-term price fluctuations, leveraging technical analysis indicators and recent market data. 
   Mid-term strategy and position development and maintenance focused on identifying momentum trends and key market events. 
   Long-term strategy and position development and maintenance analyzing fundamental factors like token valuations, onchain metrics and economic indicators can be used to identify potential long-term investment opportunities. 
  expected_output: Detailed reports on immediate, mid term and long term alpha opportunities with potential risks and rewards for crypto_trading_advisor to execute.
  async_execution: true
  agent: crypto_alpha_researcher
  tools:
  context: 
  - modelling
  - assess_risks

advise_trade_bot_executions:
  description: Generate trading bot configurations, adaptations, updates and changes, which indicate entry and exit conditions for a position based on identified patterns and research_alpha_opportunities output. 
  These trading bot configurations and subsequent adaptations, updates and changes should be across different time horizons - near-term, mid-term, and long-term. 
  Include in advised bot configurations patterns and trends in data that recommend conditions to buy, sell, or hold a particular asset based on their predicted future price movements. 
  Utilize advanced quantitative models and algorithms to make informed trading decisions.
  Continuously monitor and analyze market conditions, adjusting trading bot configurations suggestions and strategies to optimize profitability and minimize risks.
  Set up automated alerts to notify team when a model identifies a significant trading opportunity and bot configuration adaptations are needed.
  expected_output: A list of advised trade executions with rationales, tailored for {company_name}.
  async_execution: true
  agent: crypto_trading_advisor
  tools:
  context:
  - research_alpha_opportunities
  - assess_risks
  - manage_asset_portfolio

manage_asset_portfolio:
  description: Oversee and evaluate asset allocations and portoflio performance to ensure alignment with financial objectives. 
    Define investment or financial goals and risk tolerance.
    Backtest bot configurations, strategies and models so they are rigorously tested on historical data to ensure their effectiveness before and while they're implemented in live markets. 
  expected_output: An updated asset portfolio strategy that optimizes returns for {company_name}.
  async_execution: true
  agent: crypto_portfolio_manager
  tools:
  context:
  - advise_trade_executions
  - assess_risks
  - research_alpha_opportunities
  - modelling

assess_risks:
  description: Monitor and assess financial and other portfoliorisks, generating mitigation strategies.
  expected_output: A risk assessment report with mitigation strategies
  async_execution: true
  tools:
  agent: crypto_risk_assessor
  context:
  - advise_trade_executions

modelling::
  description: Using statistical methods, develop mathematical models that can predict future short, mid and long term price movements based on historical data patterns. 
  expected_output: 
  async_execution: true
  agent: crypto_alpha_researcher
  tools:
  context: 
  -